/**
BUSINESS REQUIREMENTS:

PERFORM SCD TYPE 2 TO MAINTAIN HISTORICAL DATA BY CREATING NEW RECORDS FOR EACH CHANGE, ENSURING THAT NO HISTORICAL DATA IS LOST.

NOTE: USE THE MERGE OPERATION

**/

USE EmadeDev

--SCD TYPE PROJECT 1: OFFICE_ITEMS
--CHECK TABLES  
SELECT * FROM EMADE_OFFICE_ITEMS    
SELECT * FROM STG_EMADE_OFFICE_ITEMS

--RUN ALTER TARGET AND ADD IS_ACTIVE COLUMN
ALTER TABLE EMADE_OFFICE_ITEMS ADD IS_ACTIVE VARCHAR(50)
--SCD TYPE 2 IMPLEMENTATION 
INSERT INTO EMADE_OFFICE_ITEMS (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_OFFICE_ITEMS AS TARGET
    USING STG_EMADE_OFFICE_ITEMS AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND SOURCE.IS_ACTIVE = 'Y'
    WHEN MATCHED THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N'
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, SOURCE.IS_ACTIVE)
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        SOURCE.IS_ACTIVE
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';


--SCD TYPE -- PROJECT 2: EMADE_SNACKS
--CHECK TABLES  
SELECT * FROM EMADE_SNACKS    
SELECT * FROM STG_EMADE_SNACKS


--SCD TYPE 2 IMPLEMENTATION 
INSERT INTO EMADE_SNACKS (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE 
FROM (
    MERGE INTO EMADE_SNACKS AS TARGET
    USING STG_EMADE_SNACKS AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND TARGET.IS_ACTIVE = 'Y'
    WHEN MATCHED THEN
        UPDATE SET 
            TARGET.IS_ACTIVE = 'N',
           -- TARGET.END_DATE = GETDATE() OR USE SYSTEM TIME WITH CAST(GETDATE() AS DATE)
		    TARGET.ENDDATE = DATEADD(day,-1,CAST(GETDATE() AS DATE))
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, CAST(GETDATE() AS DATE), NULL, 'Y')
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        CAST(GETDATE() AS DATE),
        NULL,
        'Y'
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';
